name: Release Workflow

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Generate tag, release name, and body
      run: |
        TAG_NAME="v$(jq -r '.version' package.json)"
        RELEASE_NAME="Release $TAG_NAME"
        BODY=$(sed -n "/## Version $(jq -r '.version' package.json | sed 's/\./\\\./g')/,/##/p" CHANGELOG.md | sed '1d;/^##/d')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
        echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
        echo "$BODY" >> release.md
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        allowUpdates: true
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        bodyFile: release.md
        draft: false
        prerelease: false