name: Release Workflow

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Generate tag, release name, and body
      run: |
        TAG_NAME="v$(jq -r '.version' package.json)"
        RELEASE_NAME="Release $TAG_NAME"
        BODY=$(sed -n "/## Version $(jq -r '.version' package.json | sed 's/\./\\\./g')/,/##/p" CHANGELOG.md | sed '1d;/^##/d')
        echo "::set-env name=TAG_NAME::$TAG_NAME"
        echo "::set-env name=RELEASE_NAME::$RELEASE_NAME"
        echo "::set-env name=RELEASE_BODY::$BODY"
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        body: |
          ${{ env.RELEASE_BODY }}
        draft: false
        prerelease: false
    - name: Publish release
      uses: actions/github-script@v4
      with:
        script: |
          const { owner, repo } = context.repo;
          const response = await github.repos.listReleases({ owner, repo, per_page: 1, draft: false, });
          const latestRelease = response.data[0];
          await github.repos.updateRelease({ owner, repo, release_id: latestRelease.id, draft: false, prerelease: false });
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}